mysite/blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    MyPostsListView,
)
app_name = "blog"

urlpatterns = [

    path('<int:pk>/', PostDetailView.as_view(), name='blog-detail'),
    path('', PostListView.as_view(), name='blog-home'),
    path('new/', PostCreateView.as_view(), name='blog-create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='blog-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='blog-delete'),
    path('my-posts/', MyPostsListView.as_view(), name='my-posts'),

]

mysite/books/urls.py
from django.urls import path
from .views import (
    BookCreate,
    IndexView,
    BookDetailView,
    BookUpdate,
    BookDeleteView,
)


app_name = 'books'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('add/', BookCreate.as_view(), name='add-book'),
    path('<int:pk>/update/', BookUpdate.as_view(), name='update-book'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='delete-book'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mysite'

urlpatterns = [
    path('', redirect_view),
    path('books/', include('books.urls', namespace="books")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('users/', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/books/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.
#DB


class Book(models.Model):
    def __str__(self):
        return self.name + '-' + self.author

    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    book_image = models.CharField(max_length=1000)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('books:index')


class FavouriteBooks(models.Model):
    bookid = models.IntegerField(default=0)
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)

mysite/books/views.py
# Create your views here.
# Front end

#
# def index(request):
#     all_books_list = Book.objects.all()
#     context = {'all_books_list': all_books_list}
#     return render(request, 'books/index.html', context)
#
#
# def details(request, book_id):
#     book = get_object_or_404(Book, pk=book_id)
#     return render(request, 'books/details.html', {'book': book})
#
#
# def info(request, book_id):
#     return HttpResponse("<h2> This is detail info of book no %s </h2>" % str(book_id))
#
#
# def read(request, book_id):
#     return HttpResponse("<h2> Reading book no %s </h2>" % str(book_id))


from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Book


class IndexView(ListView):
    model = Book
    template_name = 'books/index.html'
    ordering = ['-id']


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    template_name = 'books/book_form.html'
    fields = ['name', 'author', 'price']

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class BookUpdate(LoginRequiredMixin,  UpdateView):
    model = Book
    template_name = 'books/update-book.html'
    fields = ['name', 'author', 'price']

    def get_success_url(self):
        return reverse('books:detail', args=[self.get_object().id])

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)

    def test_func(self):
        book = self.get_object()
        if self.request.user == book.creator:
            return True
        return False


class BookDetailView(DetailView):
    model = Book
    template_name = 'books/details.html'


class BookDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Book
    template_name = 'books/delete-book.html'
    success_url = '/books'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.creator:
            return True
        return False

mysite/books/templates/books/book_form.html
{% extends 'mysite/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="body-block ">
    <div class="content-section create-form">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Book</legend>
                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-lg" type="submit">Add</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

mysite/books/templates/books/delete-book.html
{% extends 'mysite/base.html' %}

{% block body %}
<div class="body-block">
    <div class="content-section create-form">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Book</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn  btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-secondary btn-lg" href="{% url 'books:detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
    </div>

{% endblock %}

mysite/books/templates/books/details.html
{% extends 'mysite/base.html' %}

{% block body %}
<div class="body-block">

    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <p>
                    <a  class="btn btn-link" href="{% url 'books:index' %}">←Back</a>
                    {%if object.creator == user %}
                    <a href="{% url 'books:delete-book' object.id %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                    <a href="{% url 'books:update-book' object.id %}">
                    <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    {% endif %}
                </p>
                <h2>{{ book.name }}</h2>


            </div>
            <small class="text-muted">By {{ book.author }}</small>
            <small class="text-muted">₹ {{ book.price}}</small>
        </div>
    </article>

</div>
{% endblock  %}  <!--no need to use content after endblock-->

mysite/books/templates/books/index.html
{% extends 'mysite/base.html' %}

{% block top %}
{% if user.is_authenticated %}
<a href="{% url 'books:add-book' %}" class="btn btn-secondary btn-lg " role="button" aria-pressed="true">Add Book</a>
{% endif %}
{% endblock %}

{% block body %}

{% if object_list %}

<div class="body-block">
    {% for book in object_list %}

    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="/books/{{ book.id }}/">{{ book.name }}</a>
                <small class="text-muted">₹ {{ book.price }}</small>
            </div>
            <div>
                <p>
                    <small class="text-muted">By</small>
                    <a class="article-title">{{ book.author }}</a>
                </p>
            </div>

            <p class="article-content">{{ book.type }}</p>
        </div>
    </article>
    {% endfor %}
</div>
{% else %}
<p>No books are available.</p>
{% endif %}

{%endblock%}

mysite/books/templates/books/update-book.html
{% extends 'mysite/base.html' %}

{% load crispy_forms_tags %}
{% block body %}
<div class="body-block">
    <div class="content-section create-form">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Book Details</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-lg" type="submit">Update</button>
                <a class="btn btn-secondary btn-lg" href="{% url 'books:detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}