mysite/blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    MyPostsListView,
)
app_name = "blog"

urlpatterns = [

    path('<int:pk>/', PostDetailView.as_view(), name='blog-detail'),
    path('', PostListView.as_view(), name='blog-home'),
    path('new/', PostCreateView.as_view(), name='blog-create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='blog-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='blog-delete'),
    path('my-posts/', MyPostsListView.as_view(), name='my-posts'),

]

mysite/books/urls.py
from django.urls import path
from .views import (
    BookCreate,
    IndexView,
    BookDetailView,
    BookUpdate,
    BookDeleteView,
)


app_name = 'books'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('add/', BookCreate.as_view(), name='add-book'),
    path('<int:pk>/update/', BookUpdate.as_view(), name='update-book'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='delete-book'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mysite'

urlpatterns = [
    path('', redirect_view),
    path('books/', include('books.urls', namespace="books")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('users/', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'
urlpatterns = [

    path('signup/', views.register, name='myapp-signup'),
    path('success/', views.register_successful, name='signup-success'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='myapp-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='myapp-logout'),
    path('profile/', views.profile, name='profile'),

]

mysite/mysite/views.py
from django.shortcuts import redirect


def redirect_view(request):
    response = redirect('/blog/')
    return response

mysite/mysite/templates/mysite/base.html
{% load staticfiles %} <!--used to load css sheet-->


<!--This file contains all the header part of the page-->


<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
    <link href="{% static 'mysite/style.css' %}" rel="stylesheet" type="text/css">  <!--used to load css sheet-->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Mysite </title>
</head>
<body>

<div class="top-nav">{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'blog:blog-home' %}">The Blog</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:my-posts' %}">My Posts<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'books:index' %}">Books<span class="sr-only">(current)</span></a>
                </li>
                <!--<li class="nav-item active">-->
                <!--<a class="nav-link" href="#">Friends<span class="sr-only">(current)</span></a>-->
                <!--</li>-->
            </ul>
        </div>

        <div class="nav navbar-nav navbar-right element-right">
            <ul class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-primary btn-top-nav" href="{% url 'users:profile' %}" role="button">Profile</a>
                <li class="nav-item">
                    <a class="btn btn-primary btn-top-nav" href="{% url 'users:myapp-logout' %}" role="button">Log
                        out</a>
                </li>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-primary btn-top-nav" href="{% url 'users:myapp-login' %}" role="button">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-primary btn-top-nav" href="{% url 'users:myapp-signup' %}" role="button">Sign
                        Up</a>
                </li>
                {% endif %}
            </ul>
        </div>

        <!--<li class="nav-item active">-->
        <!--<a class="nav-link" href="#">My Blogs<span class="sr-only">(current)</span></a>-->
        <!--</li>-->
        <!--<li class="nav-item active">-->
        <!--<a class="nav-link" href="#">Friends<span class="sr-only">(current)</span></a>-->
        <!--</li>-->


</nav>
{% endblock %}
</div>

<div class="top-container">{% block top %}{% endblock %}</div>

<div class="container list-body">
    {% block body %}

    {% endblock %}
</div>


<script crossorigin="anonymous"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>