mysite/blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    MyPostsListView,
)
app_name = "blog"

urlpatterns = [

    path('<int:pk>/', PostDetailView.as_view(), name='blog-detail'),
    path('', PostListView.as_view(), name='blog-home'),
    path('new/', PostCreateView.as_view(), name='blog-create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='blog-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='blog-delete'),
    path('my-posts/', MyPostsListView.as_view(), name='my-posts'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mysite'

urlpatterns = [
    path('', redirect_view),
    path('books/', include('books.urls', namespace="books")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('users/', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-home')

mysite/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Post


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/list-view.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/list-view.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']


class MyPostsListView(ListView):
    model = Post
    template_name = 'blog/my-posts.html'
    context_object_name = 'myposts'
    ordering = ['-date_posted']

    def get_queryset(self):
        print(self.request.user)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post-detail.html'
    context_object_name = 'posts'


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/delete-post.html'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/create-post.html'
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/update-post.html'
    fields = ['title', 'content']

    def get_success_url(self):
        return reverse('blog:blog-detail', args=[self.get_object().id])

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

mysite/blog/templates/blog/create-post.html
{% extends 'mysite/base.html' %}

{% load crispy_forms_tags %}
{% block body %}
<div class="body-block">
    <div class="content-section create-form">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-lg" type="submit">Post</button>
            </div>
        </form>
    </div>
    </div>

{% endblock %}

mysite/blog/templates/blog/delete-post.html
{% extends 'mysite/base.html' %}

{% block body %}
<div class="body-block">
    <div class="content-section create-form">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn  btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-secondary btn-lg" href="{% url 'blog:blog-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
    </div>

{% endblock %}

mysite/blog/templates/blog/list-view.html
{% extends 'mysite/base.html' %}

{% block top %}
{% if user.is_authenticated %}
<a aria-pressed="true" class="btn btn-secondary btn-lg " href="{% url 'blog:blog-create' %}" role="button">+ Post</a>
{% endif %}
{% endblock %}

{% block body %}
<div class="body-block">
    {% for object in posts %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="/blog/{{ object.id }}/">{{ object.title }}</a>
            </div>
            <p>
                <small class="text-muted">By {{ object.author }}</small>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y"}}</small>
            </p>
        </div>
    </article>
    {% endfor %}
</div>
{% endblock  %}  <!--no need to use content after endblock-->

mysite/blog/templates/blog/my-posts.html
{% extends 'mysite/base.html' %}

{% block top %}
{% if user.is_authenticated %}
<a aria-pressed="true" class="btn btn-secondary btn-lg " href="{% url 'blog:blog-create' %}" role="button">+ Post</a>
{% endif %}
{% endblock %}

{% block body %}
<div class="body-block">

    {% for object in myposts %}
    {% if object.author == user %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="/blog/{{ object.id }}/">{{ object.title }}</a>
            </div>
            <p>
                <small class="text-muted">By {{ object.author }}</small>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y"}}</small>
            </p>
        </div>
    </article>

    {% endif %}
    {% endfor %}

</div>
{% endblock  %}  <!--no need to use content after endblock-->

mysite/blog/templates/blog/post-detail.html
{% extends 'mysite/base.html' %}

{% block body %}
<div class="body-block">

    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <p>
                    <a class="btn btn-link" href="{% url 'blog:blog-home' %}">←Back</a>
                    {% if object.author == user %}

                    <a class="view-actions" href="{% url 'blog:blog-delete' object.id %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                    <a class="view-actions" href="{% url 'blog:blog-update' object.id %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                    <a href="{% url 'blog:blog-delete' object.id %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                    <a href="{% url 'blog:blog-update' object.id %}">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    {% endif %}
                </p>
                <h2>{{ object.title }}</h2>
                <small class="text-muted">By {{ object.author }}</small>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y"}}</small>

            </div>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>

</div>
{% endblock  %}  <!--no need to use content after endblock-->

mysite/blog/templates/blog/update-post.html
{% extends 'mysite/base.html' %}

{% load crispy_forms_tags %}
{% block body %}
<div class="body-block">
    <div class="content-section create-form">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-lg" type="submit">Post</button>
                <a class="btn btn-secondary btn-lg" href="{% url 'blog:blog-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}